-- Novastyle · variantes de producto (tallas/colores con disponibilidad) y
-- lectura pública del contenido del CMS.
--
-- Dos cosas:
--   1. Tablas product_sizes / product_colors editables desde el panel, expuestas
--      en public_products_view para que la landing muestre la ficha de detalle.
--   2. Políticas de lectura pública que le faltaban a las tablas de contenido
--      (cabecera, hero, nosotras, newsletter, footer). Sin ellas la landing —que
--      lee con la clave anónima— recibía filas vacías y, por ejemplo, el menú de
--      navegación se quedaba sin enlaces.

-- 1 · Tablas de variantes -----------------------------------------------------

create table if not exists public.product_sizes (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  label text not null,
  available boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.product_colors (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  label text not null,
  swatch text,
  available boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists product_sizes_product_idx on public.product_sizes(product_id, display_order);
create index if not exists product_colors_product_idx on public.product_colors(product_id, display_order);

alter table public.product_sizes enable row level security;
alter table public.product_colors enable row level security;

-- Lectura pública solo de variantes de productos publicados.
create policy "public read sizes of published products" on public.product_sizes
  for select using (
    exists (select 1 from public.products p where p.id = product_id and p.status = 'published')
  );
create policy "public read colors of published products" on public.product_colors
  for select using (
    exists (select 1 from public.products p where p.id = product_id and p.status = 'published')
  );

-- Gestión desde el panel (usuarios autenticados).
create policy "authenticated manage product_sizes" on public.product_sizes
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "authenticated manage product_colors" on public.product_colors
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- 2 · Lectura pública del contenido del CMS -----------------------------------
-- Las secciones se leen si están publicadas; las listas, si están activas.

create policy "public read site_header" on public.site_header
  for select using (status = 'published');
create policy "public read header_links" on public.header_links
  for select using (active = true);

create policy "public read hero_section" on public.hero_section
  for select using (status = 'published');
create policy "public read hero_ctas" on public.hero_ctas
  for select using (active = true);
create policy "public read hero_stats" on public.hero_stats
  for select using (active = true);

create policy "public read about_section" on public.about_section
  for select using (status = 'published');
create policy "public read about_stats" on public.about_stats
  for select using (active = true);
create policy "public read about_values" on public.about_values
  for select using (active = true);

create policy "public read newsletter_section" on public.newsletter_section
  for select using (status = 'published');

create policy "public read footer_section" on public.footer_section
  for select using (status = 'published');
create policy "public read footer_link_groups" on public.footer_link_groups
  for select using (active = true);
create policy "public read footer_links" on public.footer_links
  for select using (active = true);
create policy "public read footer_social_links" on public.footer_social_links
  for select using (active = true);

-- 3 · Vista pública con variantes ---------------------------------------------
-- Añade sizes/colors como arrays JSON, ordenados. El resto de la vista se
-- mantiene igual que en la migración original.

create or replace view public.public_products_view as
select
  p.id,
  p.name,
  p.slug,
  p.price,
  p.color,
  p.description,
  p.sold_out,
  c.name as category_name,
  c.slug as category_slug,
  col.id as collection_id,
  col.name as collection_name,
  col.slug as collection_slug,
  t.name as tag_name,
  coalesce(primary_image.image_url, first_image.image_url) as image_url,
  promo.percentage as promotion_percentage,
  case
    when promo.percentage is null then null
    else round(p.price * (100 - promo.percentage) / 100, 2)
  end as discounted_price,
  coalesce(
    (
      select json_agg(json_build_object('label', s.label, 'available', s.available)
                      order by s.display_order, s.id)
      from public.product_sizes s
      where s.product_id = p.id
    ),
    '[]'::json
  ) as sizes,
  coalesce(
    (
      select json_agg(json_build_object('label', cc.label, 'available', cc.available, 'swatch', cc.swatch)
                      order by cc.display_order, cc.id)
      from public.product_colors cc
      where cc.product_id = p.id
    ),
    '[]'::json
  ) as colors
from public.products p
join public.categories c on c.id = p.category_id and c.status = 'published'
left join public.collections col on col.id = p.collection_id and col.status = 'published'
left join public.tags t on t.id = p.tag_id and t.status = 'published'
left join lateral (
  select pi.image_url
  from public.product_images pi
  where pi.product_id = p.id and pi.is_primary
  limit 1
) primary_image on true
left join lateral (
  select pi.image_url
  from public.product_images pi
  where pi.product_id = p.id
  order by pi.display_order, pi.id
  limit 1
) first_image on true
left join lateral (
  select pr.percentage
  from public.promotions pr
  where pr.status = 'published'
    and now() between pr.starts_at and pr.ends_at
    and (
      (pr.scope = 'product' and exists (
        select 1 from public.promotion_products pp
        where pp.promotion_id = pr.id and pp.product_id = p.id
      ))
      or (pr.scope = 'category' and exists (
        select 1 from public.promotion_categories pc
        where pc.promotion_id = pr.id and pc.category_id = p.category_id
      ))
      or (pr.scope = 'collection' and p.collection_id is not null and exists (
        select 1 from public.promotion_collections pcl
        where pcl.promotion_id = pr.id and pcl.collection_id = p.collection_id
      ))
    )
  order by
    case pr.scope when 'product' then 1 when 'collection' then 2 else 3 end,
    pr.percentage desc
  limit 1
) promo on true
where p.status = 'published';

-- 4 · Seed de variantes de los 8 productos existentes -------------------------
-- Coincide con lib/mock-data.ts. Idempotente: no duplica si ya hay filas.

insert into public.product_sizes (product_id, label, available, display_order)
select * from (values
  (1,'XS',false,1),(1,'S',true,2),(1,'M',true,3),(1,'L',true,4),(1,'XL',true,5),
  (2,'XS',true,1),(2,'S',true,2),(2,'M',true,3),(2,'L',false,4),(2,'XL',true,5),(2,'XXL',true,6),
  (3,'S',true,1),(3,'M',true,2),(3,'L',false,3),
  (4,'S',true,1),(4,'M',true,2),(4,'L',true,3),(4,'XL',true,4),(4,'XXL',true,5),
  (5,'XS',false,1),(5,'S',true,2),(5,'M',true,3),(5,'L',true,4),(5,'XL',false,5),
  (6,'XS',false,1),(6,'S',false,2),(6,'M',false,3),(6,'L',false,4),
  (7,'XS',true,1),(7,'S',true,2),(7,'M',true,3),(7,'L',true,4),(7,'XL',true,5),(7,'XXL',false,6),
  (8,'S',true,1),(8,'M',true,2),(8,'L',true,3),(8,'XL',true,4),(8,'XXL',true,5),(8,'3XL',true,6)
) as v(product_id, label, available, display_order)
where not exists (select 1 from public.product_sizes);

insert into public.product_colors (product_id, label, swatch, available, display_order)
select * from (values
  (1,'Arena','#d9c7a8',true,1),(1,'Blanco roto','#efe7d6',true,2),(1,'Terracota','#b5623c',false,3),
  (2,'Crudo','#ede4d3',true,1),(2,'Negro','#1a1714',true,2),
  (3,'Carmesí','#9e2b25',true,1),(3,'Vino','#5b2130',false,2),
  (4,'Gris','#8a8a88',true,1),(4,'Negro','#1a1714',true,2),(4,'Camel','#b08d57',true,3),
  (5,'Camel','#b08d57',true,1),(5,'Negro','#1a1714',true,2),(5,'Arena','#d9c7a8',false,3),
  (6,'Blanco','#f2ece0',false,1),
  (7,'Estampado crema','linear-gradient(135deg,#e9dfc9,#c9a98a,#8aa9c9)',true,1),(7,'Estampado azul','linear-gradient(135deg,#c9d3e0,#7c93b5,#3f5878)',true,2),
  (8,'Azul','#6e86a8',true,1),(8,'Blanco','#efe7d6',true,2),(8,'Celeste','#afc3d6',false,3)
) as v(product_id, label, swatch, available, display_order)
where not exists (select 1 from public.product_colors);
