create extension if not exists pgcrypto;
create extension if not exists unaccent;
create extension if not exists citext;

create type content_status as enum ('draft', 'published');
create type promotion_scope as enum ('product', 'category', 'collection');

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.slugify(value text)
returns text
language sql
immutable
as $$
  select trim(both '-' from regexp_replace(lower(unaccent(coalesce(value, ''))), '[^a-z0-9]+', '-', 'g'));
$$;

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  display_order integer not null default 0,
  status content_status not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.tags (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  display_order integer not null default 0,
  status content_status not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.collections (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  badge_label text not null,
  description text not null,
  image_url text not null,
  display_order integer not null default 0,
  status content_status not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  price numeric(10,2) not null check (price >= 0),
  color text not null,
  description text,
  sold_out boolean not null default false,
  status content_status not null default 'draft',
  category_id bigint not null references public.categories(id),
  collection_id bigint references public.collections(id),
  tag_id bigint references public.tags(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  image_url text not null,
  alt text,
  display_order integer not null default 0,
  is_primary boolean not null default false,
  created_at timestamptz not null default now()
);

create unique index one_primary_product_image
  on public.product_images(product_id)
  where is_primary;

create table public.promotions (
  id bigint generated by default as identity primary key,
  name text not null,
  percentage integer not null check (percentage > 0 and percentage < 100),
  scope promotion_scope not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status content_status not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create table public.promotion_products (
  promotion_id bigint not null references public.promotions(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  primary key (promotion_id, product_id)
);

create table public.promotion_categories (
  promotion_id bigint not null references public.promotions(id) on delete cascade,
  category_id bigint not null references public.categories(id) on delete cascade,
  primary key (promotion_id, category_id)
);

create table public.promotion_collections (
  promotion_id bigint not null references public.promotions(id) on delete cascade,
  collection_id bigint not null references public.collections(id) on delete cascade,
  primary key (promotion_id, collection_id)
);

create table public.subscribers (
  id bigint generated by default as identity primary key,
  email citext not null unique,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table public.site_header (
  id boolean primary key default true check (id),
  logo_text text not null,
  status content_status not null default 'published',
  updated_at timestamptz not null default now()
);

create table public.header_links (
  id bigint generated by default as identity primary key,
  label text not null,
  href text not null unique,
  display_order integer not null,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table public.hero_section (
  id boolean primary key default true check (id),
  badge_text text not null,
  title_prefix text not null,
  title_emphasis text not null,
  title_suffix text not null,
  description text not null,
  featured_product_id bigint references public.products(id),
  status content_status not null default 'published',
  updated_at timestamptz not null default now()
);

create table public.hero_ctas (
  id bigint generated by default as identity primary key,
  label text not null,
  href text not null,
  variant text not null check (variant in ('primary', 'secondary')),
  display_order integer not null,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table public.hero_stats (
  id bigint generated by default as identity primary key,
  value text not null,
  label text not null,
  display_order integer not null,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table public.about_section (
  id boolean primary key default true check (id),
  badge_text text not null,
  title text not null,
  body text not null,
  image_url text not null,
  floating_quote text not null,
  status content_status not null default 'published',
  updated_at timestamptz not null default now()
);

create table public.about_stats (
  id bigint generated by default as identity primary key,
  value text not null,
  label text not null,
  display_order integer not null,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table public.about_values (
  id bigint generated by default as identity primary key,
  icon text not null check (icon in ('leaf', 'scissors', 'heart', 'map-pin')),
  title text not null,
  description text not null,
  display_order integer not null,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table public.newsletter_section (
  id boolean primary key default true check (id),
  badge_text text not null,
  title text not null,
  description text not null,
  button_text text not null,
  privacy_note text not null,
  status content_status not null default 'published',
  updated_at timestamptz not null default now()
);

create table public.footer_section (
  id boolean primary key default true check (id),
  logo_text text not null,
  description text not null,
  status content_status not null default 'published',
  updated_at timestamptz not null default now()
);

create table public.footer_link_groups (
  id bigint generated by default as identity primary key,
  title text not null,
  display_order integer not null,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table public.footer_links (
  id bigint generated by default as identity primary key,
  group_id bigint references public.footer_link_groups(id) on delete cascade,
  kind text not null default 'group' check (kind in ('group', 'legal')),
  label text not null,
  href text,
  display_order integer not null,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table public.footer_social_links (
  id bigint generated by default as identity primary key,
  platform text not null check (platform in ('instagram', 'facebook')),
  href text,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create index products_status_idx on public.products(status);
create index products_category_id_idx on public.products(category_id);
create index products_collection_id_idx on public.products(collection_id);
create index collections_status_order_idx on public.collections(status, display_order);
create index categories_status_order_idx on public.categories(status, display_order);
create index tags_status_order_idx on public.tags(status, display_order);
create index promotions_status_dates_idx on public.promotions(status, starts_at, ends_at);

create trigger categories_updated_at before update on public.categories for each row execute function public.set_updated_at();
create trigger tags_updated_at before update on public.tags for each row execute function public.set_updated_at();
create trigger collections_updated_at before update on public.collections for each row execute function public.set_updated_at();
create trigger products_updated_at before update on public.products for each row execute function public.set_updated_at();
create trigger promotions_updated_at before update on public.promotions for each row execute function public.set_updated_at();

create or replace view public.public_products_view as
select
  p.id,
  p.name,
  p.slug,
  p.price,
  p.color,
  p.description,
  p.sold_out,
  c.name as category_name,
  c.slug as category_slug,
  col.id as collection_id,
  col.name as collection_name,
  col.slug as collection_slug,
  t.name as tag_name,
  coalesce(primary_image.image_url, first_image.image_url) as image_url,
  promo.percentage as promotion_percentage,
  case
    when promo.percentage is null then null
    else round(p.price * (100 - promo.percentage) / 100, 2)
  end as discounted_price
from public.products p
join public.categories c on c.id = p.category_id and c.status = 'published'
left join public.collections col on col.id = p.collection_id and col.status = 'published'
left join public.tags t on t.id = p.tag_id and t.status = 'published'
left join lateral (
  select pi.image_url
  from public.product_images pi
  where pi.product_id = p.id and pi.is_primary
  limit 1
) primary_image on true
left join lateral (
  select pi.image_url
  from public.product_images pi
  where pi.product_id = p.id
  order by pi.display_order, pi.id
  limit 1
) first_image on true
left join lateral (
  select pr.percentage
  from public.promotions pr
  where pr.status = 'published'
    and now() between pr.starts_at and pr.ends_at
    and (
      (pr.scope = 'product' and exists (
        select 1 from public.promotion_products pp
        where pp.promotion_id = pr.id and pp.product_id = p.id
      ))
      or (pr.scope = 'category' and exists (
        select 1 from public.promotion_categories pc
        where pc.promotion_id = pr.id and pc.category_id = p.category_id
      ))
      or (pr.scope = 'collection' and p.collection_id is not null and exists (
        select 1 from public.promotion_collections pcl
        where pcl.promotion_id = pr.id and pcl.collection_id = p.collection_id
      ))
    )
  order by
    case pr.scope when 'product' then 1 when 'collection' then 2 else 3 end,
    pr.percentage desc
  limit 1
) promo on true
where p.status = 'published';

create or replace view public.public_collections_view as
select
  col.id,
  col.name,
  col.slug,
  col.badge_label,
  col.description,
  col.image_url,
  col.display_order,
  count(p.id)::integer as item_count
from public.collections col
left join public.products p on p.collection_id = col.id and p.status = 'published'
where col.status = 'published'
group by col.id
order by col.display_order, col.id;

alter table public.categories enable row level security;
alter table public.tags enable row level security;
alter table public.collections enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.promotions enable row level security;
alter table public.promotion_products enable row level security;
alter table public.promotion_categories enable row level security;
alter table public.promotion_collections enable row level security;
alter table public.subscribers enable row level security;
alter table public.site_header enable row level security;
alter table public.header_links enable row level security;
alter table public.hero_section enable row level security;
alter table public.hero_ctas enable row level security;
alter table public.hero_stats enable row level security;
alter table public.about_section enable row level security;
alter table public.about_stats enable row level security;
alter table public.about_values enable row level security;
alter table public.newsletter_section enable row level security;
alter table public.footer_section enable row level security;
alter table public.footer_link_groups enable row level security;
alter table public.footer_links enable row level security;
alter table public.footer_social_links enable row level security;

create policy "public read published categories" on public.categories for select using (status = 'published');
create policy "public read published tags" on public.tags for select using (status = 'published');
create policy "public read published collections" on public.collections for select using (status = 'published');
create policy "public read published products" on public.products for select using (status = 'published');
create policy "public read published product images" on public.product_images for select using (
  exists (select 1 from public.products p where p.id = product_id and p.status = 'published')
);
create policy "public subscribe" on public.subscribers for insert with check (true);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'categories','tags','collections','products','product_images','promotions',
    'promotion_products','promotion_categories','promotion_collections','subscribers',
    'site_header','header_links','hero_section','hero_ctas','hero_stats','about_section',
    'about_stats','about_values','newsletter_section','footer_section',
    'footer_link_groups','footer_links','footer_social_links'
  ]
  loop
    execute format('create policy %I on public.%I for all using (auth.role() = ''authenticated'') with check (auth.role() = ''authenticated'')', 'authenticated manage ' || table_name, table_name);
  end loop;
end $$;

insert into storage.buckets (id, name, public)
values ('novastyle', 'novastyle', true)
on conflict (id) do update set public = excluded.public;

create policy "public read novastyle assets"
on storage.objects for select
using (bucket_id = 'novastyle');

create policy "authenticated manage novastyle assets"
on storage.objects for all
using (bucket_id = 'novastyle' and auth.role() = 'authenticated')
with check (bucket_id = 'novastyle' and auth.role() = 'authenticated');

insert into public.categories (id, name, slug, display_order, status) values
  (1, 'Vestidos', 'vestidos', 1, 'published'),
  (2, 'Blusas', 'blusas', 2, 'published'),
  (3, 'Pantalones', 'pantalones', 3, 'published'),
  (4, 'Accesorios', 'accesorios', 4, 'published'),
  (5, 'Outerwear', 'outerwear', 5, 'published')
on conflict (id) do nothing;

insert into public.tags (id, name, slug, display_order, status) values
  (1, 'Nuevo', 'nuevo', 1, 'published'),
  (2, 'Popular', 'popular', 2, 'published'),
  (3, 'Últimas unidades', 'ultimas-unidades', 3, 'published'),
  (4, 'Edición limitada', 'edicion-limitada', 4, 'published')
on conflict (id) do nothing;

insert into public.collections (id, name, slug, badge_label, description, image_url, display_order, status) values
  (1, 'Verano 2026', 'verano-2026', 'Nueva temporada', 'Livianos, frescos y llenos de color.', '/images/productos/camisa-oversize.jpg', 1, 'published'),
  (2, 'Noche', 'noche', 'Ocasiones especiales', 'Para los momentos que merecen brillar.', '/images/colecciones/noche.jpg', 2, 'published'),
  (3, 'Esenciales', 'esenciales', 'Atemporal', 'Lo que nunca pasa de moda. Básicos con alma.', '/images/productos/blazer-sastre.jpg', 3, 'published')
on conflict (id) do nothing;

insert into public.products (id, name, slug, price, color, description, sold_out, status, category_id, collection_id, tag_id) values
  (1, 'Vestido Lino Natural', 'vestido-lino-natural', 189, 'Arena', null, false, 'published', 1, 3, 1),
  (2, 'Blusa Seda Cruda', 'blusa-seda-cruda', 129, 'Crudo', null, false, 'published', 2, 3, 2),
  (3, 'Vestido Carmesí', 'vestido-carmesi', 229, 'Rojo', null, false, 'published', 1, 2, 3),
  (4, 'Blazer Sastre', 'blazer-sastre', 299, 'Gris', null, false, 'published', 5, 3, 1),
  (5, 'Pantalón Wide Leg', 'pantalon-wide-leg', 159, 'Camel', null, false, 'published', 3, 3, null),
  (6, 'Blusa Bordada', 'blusa-bordada', 139, 'Blanco', null, true, 'published', 2, 1, 4),
  (7, 'Vestido Midi Floral', 'vestido-midi-floral', 199, 'Multicolor', null, false, 'published', 1, 2, 1),
  (8, 'Camisa Oversize', 'camisa-oversize', 115, 'Azul', null, false, 'published', 2, 1, null)
on conflict (id) do nothing;

insert into public.product_images (product_id, image_url, alt, display_order, is_primary)
select product_id, image_url, alt, display_order, is_primary
from (values
  (1, '/images/productos/blusa-bordada.jpg', 'Vestido Lino Natural', 1, true),
  (2, '/images/productos/blusa-seda-cruda.jpg', 'Blusa Seda Cruda', 1, true),
  (3, '/images/productos/vestido-carmesi.jpg', 'Vestido Carmesí', 1, true),
  (4, '/images/productos/blazer-sastre.jpg', 'Blazer Sastre', 1, true),
  (5, '/images/colecciones/esenciales.jpg', 'Pantalón Wide Leg', 1, true),
  (6, '/images/colecciones/verano-2026.jpg', 'Blusa Bordada', 1, true),
  (7, '/images/colecciones/noche.jpg', 'Vestido Midi Floral', 1, true),
  (8, '/images/productos/camisa-oversize.jpg', 'Camisa Oversize', 1, true)
) as seed(product_id, image_url, alt, display_order, is_primary)
where not exists (
  select 1
  from public.product_images existing
  where existing.product_id = seed.product_id
    and existing.is_primary
);

insert into public.site_header (id, logo_text, status) values (true, 'Novastyle', 'published')
on conflict (id) do update set logo_text = excluded.logo_text;

insert into public.header_links (label, href, display_order, active) values
  ('Colecciones', '#colecciones', 1, true),
  ('Catálogo', '#catalogo', 2, true),
  ('Sobre nosotras', '#sobre-nosotras', 3, true),
  ('Contacto', '#contacto', 4, true)
on conflict (href) do nothing;

insert into public.hero_section
  (id, badge_text, title_prefix, title_emphasis, title_suffix, description, featured_product_id, status)
values
  (true, 'Colección Verano 2026 · Hecho en Perú', 'Moda que', 'cuenta', 'una historia',
  'Prendas pensadas para mujeres reales. Diseños únicos, tejidos naturales y producción local — porque la moda debería sentirse tan bien como verse.',
  3, 'published')
on conflict (id) do nothing;

insert into public.hero_ctas (label, href, variant, display_order, active) values
  ('Ver catálogo', '#catalogo', 'primary', 1, true),
  ('Ver colecciones', '#colecciones', 'secondary', 2, true);

insert into public.hero_stats (value, label, display_order, active) values
  ('200+', 'Prendas únicas', 1, true),
  ('100%', 'Producción local', 2, true),
  ('4 años', 'Vistiendo sueños', 3, true);

insert into public.about_section
  (id, badge_text, title, body, image_url, floating_quote, status)
values
  (true, 'Nuestra historia', 'Nació de un sueño, creció con amor',
  'Novastyle nació en 2022 desde el taller de casa de Valentina, en Lima, con una máquina de coser heredada y la certeza de que la moda peruana podía ser diferente: más honesta, más bonita, más cercana.

Hoy somos un equipo de 6 mujeres apasionadas que diseñan, cosen y empacan cada pedido con el mismo cuidado del primer día. Cada prenda lleva horas de trabajo, materiales elegidos con criterio y mucho cariño.',
  '/images/secciones/taller.jpg', 'Moda que se siente bien por dentro y por fuera.', 'published')
on conflict (id) do nothing;

insert into public.about_stats (value, label, display_order, active) values
  ('6', 'Mujeres', 1, true),
  ('2.400+', 'Clientas felices', 2, true),
  ('100%', 'Hecho a mano', 3, true);

insert into public.about_values (icon, title, description, display_order, active) values
  ('leaf', 'Materiales conscientes', 'Usamos linos, algodones orgánicos y telas naturales que cuidan tanto tu piel como el planeta.', 1, true),
  ('scissors', 'Producción local', 'Cada prenda se confecciona a mano por talleristas locales. Apoyamos el trabajo justo y la economía cercana.', 2, true),
  ('heart', 'Diseño inclusivo', 'Tallas del XS al 3XL. Porque la moda bonita no debería tener límites de talla.', 3, true);

insert into public.newsletter_section
  (id, badge_text, title, description, button_text, privacy_note, status)
values
  (true, 'Comunidad Novastyle', 'Sé la primera en saberlo',
  'Nuevos ingresos, preventas exclusivas, descuentos para suscriptoras y detrás de escena del taller. Nada de spam, solo lo lindo.',
  'Suscribirme', 'Sin spam · Cancelas cuando quieras · Solo lo bueno', 'published')
on conflict (id) do nothing;

insert into public.footer_section (id, logo_text, description, status)
values (true, 'Novastyle', 'Moda consciente, hecha a mano, diseñada para ti.', 'published')
on conflict (id) do nothing;

insert into public.footer_link_groups (id, title, display_order, active) values
  (1, 'Tienda', 1, true),
  (2, 'Info', 2, true),
  (3, 'Contacto', 3, true)
on conflict (id) do nothing;

insert into public.footer_links (group_id, kind, label, href, display_order, active) values
  (1, 'group', 'Novedades', null, 1, true),
  (1, 'group', 'Colecciones', '#colecciones', 2, true),
  (1, 'group', 'Catálogo completo', '#catalogo', 3, true),
  (1, 'group', 'Preventas', null, 4, true),
  (1, 'group', 'Liquidación', null, 5, true),
  (2, 'group', 'Sobre nosotras', '#sobre-nosotras', 1, true),
  (2, 'group', 'Cómo comprar', null, 2, true),
  (2, 'group', 'Tallas y medidas', null, 3, true),
  (2, 'group', 'Envíos y devoluciones', null, 4, true),
  (2, 'group', 'Preguntas frecuentes', null, 5, true),
  (3, 'group', 'hola@novastyle.pe', 'mailto:hola@novastyle.pe', 1, true),
  (3, 'group', 'WhatsApp', null, 2, true),
  (3, 'group', 'Instagram DM', null, 3, true),
  (3, 'group', 'Lunes a viernes 9-18h', null, 4, true),
  (null, 'legal', 'Términos', null, 1, true),
  (null, 'legal', 'Privacidad', null, 2, true),
  (null, 'legal', 'Cookies', null, 3, true);

insert into public.footer_social_links (platform, href, active) values
  ('instagram', null, true),
  ('facebook', null, true);
